In [12]:
import os
from dotenv import load_dotenv
load_dotenv()
MAP_KEY = os.getenv('MAP_KEY')
# Let's set your map key that was emailed to you. It should look something like 'abcdef1234567890abcdef1234567890'

# MAP_KEY = 'abcdef0123456789abcdef1234567890'

# now let's check how many transactions we have
import pandas as pd
import requests
url = 'https://firms.modaps.eosdis.nasa.gov/mapserver/mapkey_status/?MAP_KEY=' + MAP_KEY
try:
  response = requests.get(url)
  data = response.json()
  df = pd.Series(data)
  display(df)
except:
  # possible error, wrong MAP_KEY value, check for extra quotes, missing letters
  print ("There is an issue with the query. \nTry in your browser: %s" % url)

transaction_limit             5000
current_transactions            82
transaction_interval    10 minutes
dtype: object

In [2]:
# let's create a simple function that tells us how many transactions we have used.
# We will use this in later examples

def get_transaction_count() :
  count = 0
  try:
    response = requests.get(url)
    data = response.json()
    df = pd.Series(data)
    count = df['current_transactions']
  except:
    print ("Error in our call.")
  return count

tcount = get_transaction_count()
print ('Our current transaction count is %i' % tcount)

Our current transaction count is 0

In [3]:
# let's query data_availability to find out what date range is available for various datasets
# we will explain these datasets a bit later

# this url will return information about all supported sensors and their corresponding datasets
# instead of 'all' you can specify individual sensor, ex:LANDSAT_NRT
da_url = 'https://firms.modaps.eosdis.nasa.gov/api/data_availability/csv/' + MAP_KEY + '/all'
df = pd.read_csv(da_url)
display(df)

             data_id    min_date    max_date
0          MODIS_NRT  2025-10-01  2026-02-06
1           MODIS_SP  2000-11-01  2025-09-30
2   VIIRS_NOAA20_NRT  2025-11-01  2026-02-06
3    VIIRS_NOAA20_SP  2018-04-01  2025-10-31
4   VIIRS_NOAA21_NRT  2024-01-17  2026-02-06
5     VIIRS_SNPP_NRT  2025-11-01  2026-02-06
6      VIIRS_SNPP_SP  2012-01-20  2025-10-31
7        LANDSAT_NRT  2022-06-20  2026-02-06
8           GOES_NRT  2022-08-09  2026-02-06
9           BA_MODIS  2000-11-01  2025-10-01
10          BA_VIIRS  2012-03-01  2025-10-01

In [7]:
# in this example let's look at VIIRS NOAA-20, entire world and the most recent day
area_url = (
    'https://firms.modaps.eosdis.nasa.gov/api/area/csv/'
    + MAP_KEY +
    '/VIIRS_NOAA20_NRT/USA/1'
)
start_count = get_transaction_count()
df_area = pd.read_csv(area_url)
end_count = get_transaction_count()
print ('We used %i transactions.' % (end_count-start_count))

df_area

We used 0 transactions.

Empty DataFrame
Columns: [Invalid area. Expects: [west, south, east, north].]
Index: []